### ISSUE TITLE
Add support for streaming API

### ISSUE THREAD

**Issue by chafey** [ipld/js-codec-interface#4]
It would be great if codecs could support encoding to a stream and decoding from a stream.  The newish Streams API brings streaming to browsers so it could be the api to use to support nodeks and browsers:
https://developer.mozilla.org/en-US/docs/Web/API/Streams_API

**Comment by mikeal** [comment]
There’s quite a few threads on this but most of them were resolved so long ago they are not very easy to find.

Blocks have to be atomic, and encoding/decoding them atomically rather than streaming can be done faster if we embrace that constraint.

Anything that we would want to “stream” should really be chunked into several blocks and streamed that way.

That said, it is a little too difficult right now to convert from a streaming interface to a block. We may want to add a convenience API to the `Block` interface, something like:

```js
Block.fromStream(stream, cid)
```

**Comment by chafey** [comment]
> Blocks have to be atomic, and encoding/decoding them atomically rather than streaming can be done faster if we embrace that constraint.

I don't understand this argument - can you elaborate?  I don't see any relationship between block atomicity and the need to fully read a block before decoding it or fully generate a block before writing it out to storage.  Not supporting streaming will make JS IPLD apps use more resources than they would otherwise (specifically memory) and can lead to stability issues under high concurrency use cases.

**Comment by mikeal** [comment]
So, there’s a choice you have to make when designing APIs and considering streams. Do you complicate the interface to allow *everything* to potentially be a stream, or do you have some layer that is atomic of which many can then be yielded to produce a stream.

We went with the later. There was a big discussion about this when we revisited the serializers for async/await in JS.

The advantage to this approach is that you get really simple synchronous encode/decode methods that return and consume Data Model. The diss-advantage is that you don’t have an obvious place to do in-place reads/writes without a full decode and you always need to buffer the full block in to memory. Since we already have upper limits on block size elsewhere, the tradeoff seemed pretty obvious.

One last thing I’ll say is that,I’ve written a lot of streaming code in JavaScript, I was even involved in designing the Node.js Stream interface in the early 2010’s. Streams are critical for limiting memory consumption when working with large amounts of data, but they aren’t actually more *efficient* in terms of computation and even latency. Buffered/batched operations are much faster, they just consume more memory (obviously).

In the case of a single Block, you already need to enforce some kind of upper boundary size limit that is going to be well below the available memory, even when considering many concurrent actors. Given this requirement, it’s worth it to consume a little extra memory temporarily and take the other performance benefits of the atomic interface. To be perfectly honest, we’re not talking about a big difference in memory consumption if you’re decoding the entire block, because all you’re doing is consuming memory you’ll then be able to GC right after you de-serialize, and if that memory is too large you’re *still* going to have an issue when streaming the decode because the de-serialized object has to fit in memory when you’re done streaming 😉

**Comment by chafey** [comment]
This makes sense if you can keep the block size down.  It seems like most IPLD objects should be on the smaller side.  The one exception to this is when dealing with large binary objects like you find in UnixFS which has a block size of 256K.  It seems like a separate streamable type interface may be better fit for this use case.  Thoughts?

**Comment by rvagg** [comment]
@chafey yes, an ideal would be to support a streaming mode for the use-cases that _need_ it (although I'm dubious that even at 256K it's going to yield meaningful benefits). The challenge is that our codecs are not designed to do this kind of thing so our whole stack avoids it. This is one of a category if similar concerns that I wouldn't mind exploring at some point but we need more control over (and more flexible) components of the entire stack.

**Comment by chafey** [comment]
Understood, thanks for your thoughts on this.  Closing
